In [7]:
import pandas as pd

In [8]:
srr = pd.read_csv("./SRR_Acc_List.txt", sep="\t", header=None)
srr

                0
0     SRR19117446
1     SRR19117447
2     SRR19117448
3     SRR19117449
4     SRR19117450
...           ...
1113  SRR19144600
1114  SRR19144601
1115  SRR19144602
1116  SRR19144603
1117  SRR19144604

[1118 rows x 1 columns]

In [16]:
metadata = pd.read_csv("./SraRunTable.txt", sep=",")
metadata = metadata[metadata["Assay Type"] == "AMPLICON"]
metadata = metadata[metadata["Sample Name"].str.contains("feces")]
metadata = metadata[metadata["Host_age"] == ">70"]
metadata = metadata[metadata["host_sex"] == "male"]

metadata = metadata.set_index("Run")
metadata = metadata[["Sample Name"]]
metadata

                Sample Name
Run
SRR19144329  CTRL_feces_084
SRR19144330  CTRL_feces_083
SRR19144334  CTRL_feces_080
SRR19144337  CTRL_feces_077
SRR19144339  CTRL_feces_075
...                     ...
SRR19144592  CTRL_feces_140
SRR19144593  CTRL_feces_139
SRR19144595  CTRL_feces_137
SRR19144596  CTRL_feces_136
SRR19144603  CTRL_feces_002

[81 rows x 1 columns]

In [17]:
metadata.sort_values("Sample Name")

                Sample Name
Run
SRR19144603  CTRL_feces_002
SRR19144419  CTRL_feces_004
SRR19144397  CTRL_feces_006
SRR19144354  CTRL_feces_007
SRR19144466  CTRL_feces_010
...                     ...
SRR19144560  PDAC_feces_021
SRR19144559  PDAC_feces_023
SRR19144554  PDAC_feces_028
SRR19144549  PDAC_feces_032
SRR19144537  PDAC_feces_044

[81 rows x 1 columns]

In [20]:
small_metadata = metadata[metadata["Sample Name"].str.contains("CTRL")].sample(10, random_state=17)
small_metadata = pd.concat([
    small_metadata, metadata[metadata["Sample Name"].str.contains("PDAC")].sample(10, random_state=17)
])
small_metadata

                Sample Name
Run
SRR19144520  CTRL_feces_118
SRR19144430  CTRL_feces_184
SRR19144587  CTRL_feces_144
SRR19144542  CTRL_feces_028
SRR19144457  CTRL_feces_100
SRR19144569  CTRL_feces_161
SRR19144523  CTRL_feces_115
SRR19144458  CTRL_feces_099
SRR19144372  CTRL_feces_207
SRR19144491  CTRL_feces_231
SRR19144481  PDAC_feces_005
SRR19144483  PDAC_feces_003
SRR19144566  PDAC_feces_015
SRR19144559  PDAC_feces_023
SRR19144554  PDAC_feces_028
SRR19144485  PDAC_feces_001
SRR19144561  PDAC_feces_020
SRR19144537  PDAC_feces_044
SRR19144475  PDAC_feces_010
SRR19144560  PDAC_feces_021

In [21]:
small_metadata.drop(["Sample Name"], axis=1).to_csv("./SRR_Acc_List.txt", header=False, index=True)

In [23]:
small_metadata.to_csv("./SraRunTable_sampled.csv", index=True)